# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'

boxes = JSON.parse(File.read(File.join(File.dirname(__FILE__), 'boxes.json')))

Vagrant.configure("2") do |config|
    boxes.drop(1).each do |box|
        config.ssh.insert_key = false
        config.ssh.forward_agent = true

        config.vm.define box['name'] do |curr|
            curr.vm.box = box['box']

            curr.vm.network "private_network", ip: box['ip']

            curr.vm.provider "virtualbox" do |vb|
                vb.name = box['name']
                # Display the VirtualBox GUI when booting the machine
                vb.gui = false
                # Customize the amount of memory on the VM:
                vb.memory = box['memory']
                vb.cpus = box['cpus']
                # make it usable from WSL:
                vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
            end

        end
    end
end