---
- hosts: default
  become: true
  roles:
    - geerlingguy.docker

  tasks:
    - name: install python dependencies
      become: true
      apt:
        update_cache: yes
        state: latest
        name: python-pip

    - name: install 'Docker SDK for Python'
      #become: true  # WILL STOP WORKING IF UNCOMMENTED
      pip:
        name: docker

    - name: "run container"
      docker_container:
        name: ng01000_petclinic
        state: started
        restart_policy: unless-stopped
        image: ng01000/petclinic:latest
        pull: true
        ports:
          - "80:8080"