---
- hosts: default
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: "install"
      apt:
        pkg:
          - ca-certificates
          - apt-transport-https

- hosts: default
  become: true
  roles:
    - geerlingguy.docker

- hosts: default
  tasks:
    - name: install python dependencies
      become: true
      apt:
        update_cache: yes
        state: latest
        name: python3-pip

    - name: install 'Docker SDK for Python'
      #become: true  # WILL STOP WORKING IF UNCOMMENTED
      pip:
        name: docker

    - name: "run container"
      docker_container:
        name: ng01000_petclinic
        state: started
        image: ng01000/petclinic:latest
        pull: true
        ports:
          - "80:8080"